kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: benchmark-operator
  namespace: benchmark
subjects:
- kind: ServiceAccount
  name: benchmark-operator
  namespace: benchmark
roleRef:
  kind: Role
  name: benchmark-operator
  apiGroup: rbac.authorization.k8s.io
